version: '3.4'

services:
  zk1:
    image: krkr/zk
    ports:
      - 2181:2181
    environment:
      - ZOO_ID=1
      - ZOO_PEERS=1=zk1:2888:3888,2=zk2:2888:3888,3=zk3:2888:3888

  zk2:
    image: krkr/zk
    ports:
      - 2182:2181
    environment:
      - ZOO_ID=2
      - ZOO_PEERS=1=zk1:2888:3888,2=zk2:2888:3888,3=zk3:2888:3888

  zk3:
    image: krkr/zk
    ports:
      - 2183:2181
    environment:
      - ZOO_ID=3
      - ZOO_PEERS=1=zk1:2888:3888,2=zk2:2888:3888,3=zk3:2888:3888
