defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":{{ HTTPS_PORT }}"
    [entryPoints.https.tls]

[web]
address = ":8080"

[acme]
email = "{{ ACME_EMAIL }}"
storage = "/data/acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
swarmmode = {{ SWARM_MODE }}
exposedbydefault = true
