FROM krkr/dops

RUN wget -q https://releases.hashicorp.com/packer/1.2.0/packer_1.2.0_linux_amd64.zip && \
    unzip packer_1.2.0_linux_amd64.zip && \
    rm packer_1.2.0_linux_amd64.zip && \
    mv packer /usr/local/bin
